export const discord = ""
export const  github = "https://github.com/jayhcrawford"
export const   instagram  = "https://www.instagram.com/jaycraw1_"
export const tiktok = "https://www.tiktok.com/@jay.harrison.craw"
export const linkedin = "https://www.linkedin.com/in/jay-crawford-prod/"